apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstdeployment
  labels:
    app: nginx
spec:
  template:
    metadata:
      name: myfirstpod
      labels:
        app: nginx
    spec:
      containers:
        - name: myfirstpod
          image: nginx:latest
  replicas: 3
  selector:
    matchLabels:
      app: nginx